# Generated by Django 5.0.6 on 2024-06-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobportal',
            old_name='Job_name',
            new_name='job',
        ),
    ]
